/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelsResponse,
} from '../models/index';
import {
    ModelsResponseFromJSON,
    ModelsResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class DiscoveryApi extends runtime.BaseAPI {

    /**
     * Returns model/version pairs currently loaded in the active registry index.
     * List available model versions
     */
    async listModelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/models`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsResponseFromJSON(jsonValue));
    }

    /**
     * Returns model/version pairs currently loaded in the active registry index.
     * List available model versions
     */
    async listModels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsResponse> {
        const response = await this.listModelsRaw(initOverrides);
        return await response.value();
    }

}
