/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateRequest,
  ErrorResponse,
  QueryRequest,
  QueryResponse,
  Record,
  ValidateRequest,
  ValidationReport,
} from '../models/index';
import {
    CreateRequestFromJSON,
    CreateRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    QueryRequestFromJSON,
    QueryRequestToJSON,
    QueryResponseFromJSON,
    QueryResponseToJSON,
    RecordFromJSON,
    RecordToJSON,
    ValidateRequestFromJSON,
    ValidateRequestToJSON,
    ValidationReportFromJSON,
    ValidationReportToJSON,
} from '../models/index';

export interface CreateRecordRequest {
    model: string;
    version: string;
    idempotencyKey: string;
    createRequest: CreateRequest;
}

export interface QueryRecordsRequest {
    model: string;
    version: string;
    queryRequest: QueryRequest;
}

export interface ValidateModelPayloadRequest {
    model: string;
    version: string;
    validateRequest: ValidateRequest;
}

/**
 * 
 */
export class ModelsApi extends runtime.BaseAPI {

    /**
     * Validates input payload and writes a new record through the configured record store adapter.
     * Validate and create a record
     */
    async createRecordRaw(requestParameters: CreateRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Record>> {
        if (requestParameters['model'] == null) {
            throw new runtime.RequiredError(
                'model',
                'Required parameter "model" was null or undefined when calling createRecord().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling createRecord().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createRecord().'
            );
        }

        if (requestParameters['createRequest'] == null) {
            throw new runtime.RequiredError(
                'createRequest',
                'Required parameter "createRequest" was null or undefined when calling createRecord().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/models/{model}/versions/{version}:create`.replace(`{${"model"}}`, encodeURIComponent(String(requestParameters['model']))).replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRequestToJSON(requestParameters['createRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecordFromJSON(jsonValue));
    }

    /**
     * Validates input payload and writes a new record through the configured record store adapter.
     * Validate and create a record
     */
    async createRecord(requestParameters: CreateRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Record> {
        const response = await this.createRecordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Applies a filter object and returns matching records provided by the record store adapter.
     * Query records for a model version
     */
    async queryRecordsRaw(requestParameters: QueryRecordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueryResponse>> {
        if (requestParameters['model'] == null) {
            throw new runtime.RequiredError(
                'model',
                'Required parameter "model" was null or undefined when calling queryRecords().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling queryRecords().'
            );
        }

        if (requestParameters['queryRequest'] == null) {
            throw new runtime.RequiredError(
                'queryRequest',
                'Required parameter "queryRequest" was null or undefined when calling queryRecords().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/models/{model}/versions/{version}:query`.replace(`{${"model"}}`, encodeURIComponent(String(requestParameters['model']))).replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueryRequestToJSON(requestParameters['queryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueryResponseFromJSON(jsonValue));
    }

    /**
     * Applies a filter object and returns matching records provided by the record store adapter.
     * Query records for a model version
     */
    async queryRecords(requestParameters: QueryRecordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueryResponse> {
        const response = await this.queryRecordsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Runs configured validators for the selected model/version and returns a merged validation report.
     * Validate payload against model rules
     */
    async validateModelPayloadRaw(requestParameters: ValidateModelPayloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationReport>> {
        if (requestParameters['model'] == null) {
            throw new runtime.RequiredError(
                'model',
                'Required parameter "model" was null or undefined when calling validateModelPayload().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling validateModelPayload().'
            );
        }

        if (requestParameters['validateRequest'] == null) {
            throw new runtime.RequiredError(
                'validateRequest',
                'Required parameter "validateRequest" was null or undefined when calling validateModelPayload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/models/{model}/versions/{version}:validate`.replace(`{${"model"}}`, encodeURIComponent(String(requestParameters['model']))).replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ValidateRequestToJSON(requestParameters['validateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ValidationReportFromJSON(jsonValue));
    }

    /**
     * Runs configured validators for the selected model/version and returns a merged validation report.
     * Validate payload against model rules
     */
    async validateModelPayload(requestParameters: ValidateModelPayloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationReport> {
        const response = await this.validateModelPayloadRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
