/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateRequest } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { QueryRequest } from '../models';
// @ts-ignore
import type { QueryResponse } from '../models';
// @ts-ignore
import type { Record } from '../models';
// @ts-ignore
import type { ValidateRequest } from '../models';
// @ts-ignore
import type { ValidationReport } from '../models';
/**
 * ModelsApi - axios parameter creator
 * @export
 */
export const ModelsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Validates input payload and writes a new record through the configured record store adapter.
         * @summary Validate and create a record
         * @param {string} model Model identifier.
         * @param {string} version Model version.
         * @param {string} idempotencyKey Client-generated key used to deduplicate retries for side-effecting requests.
         * @param {CreateRequest} createRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRecord: async (model: string, version: string, idempotencyKey: string, createRequest: CreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'model' is not null or undefined
            assertParamExists('createRecord', 'model', model)
            // verify required parameter 'version' is not null or undefined
            assertParamExists('createRecord', 'version', version)
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('createRecord', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'createRequest' is not null or undefined
            assertParamExists('createRecord', 'createRequest', createRequest)
            const localVarPath = `/models/{model}/versions/{version}:create`
                .replace(`{${"model"}}`, encodeURIComponent(String(model)))
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Applies a filter object and returns matching records provided by the record store adapter.
         * @summary Query records for a model version
         * @param {string} model Model identifier.
         * @param {string} version Model version.
         * @param {QueryRequest} queryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryRecords: async (model: string, version: string, queryRequest: QueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'model' is not null or undefined
            assertParamExists('queryRecords', 'model', model)
            // verify required parameter 'version' is not null or undefined
            assertParamExists('queryRecords', 'version', version)
            // verify required parameter 'queryRequest' is not null or undefined
            assertParamExists('queryRecords', 'queryRequest', queryRequest)
            const localVarPath = `/models/{model}/versions/{version}:query`
                .replace(`{${"model"}}`, encodeURIComponent(String(model)))
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(queryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Runs configured validators for the selected model/version and returns a merged validation report.
         * @summary Validate payload against model rules
         * @param {string} model Model identifier, for example &#x60;re-indicators-specification&#x60;.
         * @param {string} version Model version string, for example &#x60;0.0.3&#x60;.
         * @param {ValidateRequest} validateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateModelPayload: async (model: string, version: string, validateRequest: ValidateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'model' is not null or undefined
            assertParamExists('validateModelPayload', 'model', model)
            // verify required parameter 'version' is not null or undefined
            assertParamExists('validateModelPayload', 'version', version)
            // verify required parameter 'validateRequest' is not null or undefined
            assertParamExists('validateModelPayload', 'validateRequest', validateRequest)
            const localVarPath = `/models/{model}/versions/{version}:validate`
                .replace(`{${"model"}}`, encodeURIComponent(String(model)))
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(validateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ModelsApi - functional programming interface
 * @export
 */
export const ModelsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ModelsApiAxiosParamCreator(configuration)
    return {
        /**
         * Validates input payload and writes a new record through the configured record store adapter.
         * @summary Validate and create a record
         * @param {string} model Model identifier.
         * @param {string} version Model version.
         * @param {string} idempotencyKey Client-generated key used to deduplicate retries for side-effecting requests.
         * @param {CreateRequest} createRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createRecord(model: string, version: string, idempotencyKey: string, createRequest: CreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Record>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createRecord(model, version, idempotencyKey, createRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelsApi.createRecord']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Applies a filter object and returns matching records provided by the record store adapter.
         * @summary Query records for a model version
         * @param {string} model Model identifier.
         * @param {string} version Model version.
         * @param {QueryRequest} queryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async queryRecords(model: string, version: string, queryRequest: QueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.queryRecords(model, version, queryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelsApi.queryRecords']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Runs configured validators for the selected model/version and returns a merged validation report.
         * @summary Validate payload against model rules
         * @param {string} model Model identifier, for example &#x60;re-indicators-specification&#x60;.
         * @param {string} version Model version string, for example &#x60;0.0.3&#x60;.
         * @param {ValidateRequest} validateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validateModelPayload(model: string, version: string, validateRequest: ValidateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ValidationReport>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.validateModelPayload(model, version, validateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelsApi.validateModelPayload']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ModelsApi - factory interface
 * @export
 */
export const ModelsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ModelsApiFp(configuration)
    return {
        /**
         * Validates input payload and writes a new record through the configured record store adapter.
         * @summary Validate and create a record
         * @param {string} model Model identifier.
         * @param {string} version Model version.
         * @param {string} idempotencyKey Client-generated key used to deduplicate retries for side-effecting requests.
         * @param {CreateRequest} createRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRecord(model: string, version: string, idempotencyKey: string, createRequest: CreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Record> {
            return localVarFp.createRecord(model, version, idempotencyKey, createRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Applies a filter object and returns matching records provided by the record store adapter.
         * @summary Query records for a model version
         * @param {string} model Model identifier.
         * @param {string} version Model version.
         * @param {QueryRequest} queryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryRecords(model: string, version: string, queryRequest: QueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<QueryResponse> {
            return localVarFp.queryRecords(model, version, queryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Runs configured validators for the selected model/version and returns a merged validation report.
         * @summary Validate payload against model rules
         * @param {string} model Model identifier, for example &#x60;re-indicators-specification&#x60;.
         * @param {string} version Model version string, for example &#x60;0.0.3&#x60;.
         * @param {ValidateRequest} validateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateModelPayload(model: string, version: string, validateRequest: ValidateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ValidationReport> {
            return localVarFp.validateModelPayload(model, version, validateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ModelsApi - object-oriented interface
 * @export
 * @class ModelsApi
 * @extends {BaseAPI}
 */
export class ModelsApi extends BaseAPI {
    /**
     * Validates input payload and writes a new record through the configured record store adapter.
     * @summary Validate and create a record
     * @param {string} model Model identifier.
     * @param {string} version Model version.
     * @param {string} idempotencyKey Client-generated key used to deduplicate retries for side-effecting requests.
     * @param {CreateRequest} createRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApi
     */
    public createRecord(model: string, version: string, idempotencyKey: string, createRequest: CreateRequest, options?: RawAxiosRequestConfig) {
        return ModelsApiFp(this.configuration).createRecord(model, version, idempotencyKey, createRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Applies a filter object and returns matching records provided by the record store adapter.
     * @summary Query records for a model version
     * @param {string} model Model identifier.
     * @param {string} version Model version.
     * @param {QueryRequest} queryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApi
     */
    public queryRecords(model: string, version: string, queryRequest: QueryRequest, options?: RawAxiosRequestConfig) {
        return ModelsApiFp(this.configuration).queryRecords(model, version, queryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Runs configured validators for the selected model/version and returns a merged validation report.
     * @summary Validate payload against model rules
     * @param {string} model Model identifier, for example &#x60;re-indicators-specification&#x60;.
     * @param {string} version Model version string, for example &#x60;0.0.3&#x60;.
     * @param {ValidateRequest} validateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApi
     */
    public validateModelPayload(model: string, version: string, validateRequest: ValidateRequest, options?: RawAxiosRequestConfig) {
        return ModelsApiFp(this.configuration).validateModelPayload(model, version, validateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

