/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRequest
 */
export interface CreateRequest {
    /**
     * Payload to validate and persist as a new record.
     * @type {{ [key: string]: any; }}
     * @memberof CreateRequest
     */
    payload: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateRequest interface.
 */
export function instanceOfCreateRequest(value: object): value is CreateRequest {
    if (!('payload' in value) || value['payload'] === undefined) return false;
    return true;
}

export function CreateRequestFromJSON(json: any): CreateRequest {
    return CreateRequestFromJSONTyped(json, false);
}

export function CreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'payload': json['payload'],
    };
}

export function CreateRequestToJSON(json: any): CreateRequest {
    return CreateRequestToJSONTyped(json, false);
}

export function CreateRequestToJSONTyped(value?: CreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payload': value['payload'],
    };
}

