/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelVersion
 */
export interface ModelVersion {
    /**
     * Model identifier.
     * @type {string}
     * @memberof ModelVersion
     */
    id: string;
    /**
     * Model version string.
     * @type {string}
     * @memberof ModelVersion
     */
    version: string;
}

/**
 * Check if a given object implements the ModelVersion interface.
 */
export function instanceOfModelVersion(value: object): value is ModelVersion {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function ModelVersionFromJSON(json: any): ModelVersion {
    return ModelVersionFromJSONTyped(json, false);
}

export function ModelVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'version': json['version'],
    };
}

export function ModelVersionToJSON(json: any): ModelVersion {
    return ModelVersionToJSONTyped(json, false);
}

export function ModelVersionToJSONTyped(value?: ModelVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'version': value['version'],
    };
}

