/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelVersion } from './ModelVersion';
import {
    ModelVersionFromJSON,
    ModelVersionFromJSONTyped,
    ModelVersionToJSON,
    ModelVersionToJSONTyped,
} from './ModelVersion';

/**
 * 
 * @export
 * @interface ModelsResponse
 */
export interface ModelsResponse {
    /**
     * 
     * @type {Array<ModelVersion>}
     * @memberof ModelsResponse
     */
    models: Array<ModelVersion>;
}

/**
 * Check if a given object implements the ModelsResponse interface.
 */
export function instanceOfModelsResponse(value: object): value is ModelsResponse {
    if (!('models' in value) || value['models'] === undefined) return false;
    return true;
}

export function ModelsResponseFromJSON(json: any): ModelsResponse {
    return ModelsResponseFromJSONTyped(json, false);
}

export function ModelsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'models': ((json['models'] as Array<any>).map(ModelVersionFromJSON)),
    };
}

export function ModelsResponseToJSON(json: any): ModelsResponse {
    return ModelsResponseToJSONTyped(json, false);
}

export function ModelsResponseToJSONTyped(value?: ModelsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'models': ((value['models'] as Array<any>).map(ModelVersionToJSON)),
    };
}

