/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelCountResponse
 */
export interface ModelCountResponse {
    /**
     * Number of models currently indexed by the registry.
     * @type {number}
     * @memberof ModelCountResponse
     */
    modelsCount: number;
}

/**
 * Check if a given object implements the ModelCountResponse interface.
 */
export function instanceOfModelCountResponse(value: object): value is ModelCountResponse {
    if (!('modelsCount' in value) || value['modelsCount'] === undefined) return false;
    return true;
}

export function ModelCountResponseFromJSON(json: any): ModelCountResponse {
    return ModelCountResponseFromJSONTyped(json, false);
}

export function ModelCountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelCountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'modelsCount': json['models_count'],
    };
}

export function ModelCountResponseToJSON(json: any): ModelCountResponse {
    return ModelCountResponseToJSONTyped(json, false);
}

export function ModelCountResponseToJSONTyped(value?: ModelCountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'models_count': value['modelsCount'],
    };
}

