/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueryRequest
 */
export interface QueryRequest {
    /**
     * Adapter-specific filter object for query execution.
     * @type {{ [key: string]: any; }}
     * @memberof QueryRequest
     */
    filter: { [key: string]: any; };
}

/**
 * Check if a given object implements the QueryRequest interface.
 */
export function instanceOfQueryRequest(value: object): value is QueryRequest {
    if (!('filter' in value) || value['filter'] === undefined) return false;
    return true;
}

export function QueryRequestFromJSON(json: any): QueryRequest {
    return QueryRequestFromJSONTyped(json, false);
}

export function QueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'filter': json['filter'],
    };
}

export function QueryRequestToJSON(json: any): QueryRequest {
    return QueryRequestToJSONTyped(json, false);
}

export function QueryRequestToJSONTyped(value?: QueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filter': value['filter'],
    };
}

