/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecordQueryFilter } from './RecordQueryFilter';
import {
    RecordQueryFilterFromJSON,
    RecordQueryFilterFromJSONTyped,
    RecordQueryFilterToJSON,
    RecordQueryFilterToJSONTyped,
} from './RecordQueryFilter';

/**
 * 
 * @export
 * @interface QueryRequest
 */
export interface QueryRequest {
    /**
     * 
     * @type {RecordQueryFilter}
     * @memberof QueryRequest
     */
    filter: RecordQueryFilter;
}

/**
 * Check if a given object implements the QueryRequest interface.
 */
export function instanceOfQueryRequest(value: object): value is QueryRequest {
    if (!('filter' in value) || value['filter'] === undefined) return false;
    return true;
}

export function QueryRequestFromJSON(json: any): QueryRequest {
    return QueryRequestFromJSONTyped(json, false);
}

export function QueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'filter': RecordQueryFilterFromJSON(json['filter']),
    };
}

export function QueryRequestToJSON(json: any): QueryRequest {
    return QueryRequestToJSONTyped(json, false);
}

export function QueryRequestToJSONTyped(value?: QueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filter': RecordQueryFilterToJSON(value['filter']),
    };
}

