/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadyResponse
 */
export interface ReadyResponse {
    /**
     * Readiness status string.
     * @type {string}
     * @memberof ReadyResponse
     */
    status: string;
}

/**
 * Check if a given object implements the ReadyResponse interface.
 */
export function instanceOfReadyResponse(value: object): value is ReadyResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ReadyResponseFromJSON(json: any): ReadyResponse {
    return ReadyResponseFromJSONTyped(json, false);
}

export function ReadyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function ReadyResponseToJSON(json: any): ReadyResponse {
    return ReadyResponseToJSONTyped(json, false);
}

export function ReadyResponseToJSONTyped(value?: ReadyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

