/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Record
 */
export interface Record {
    /**
     * Record identifier returned by the store adapter.
     * @type {string}
     * @memberof Record
     */
    id: string;
    /**
     * Model identifier used for this record.
     * @type {string}
     * @memberof Record
     */
    model: string;
    /**
     * Model version used for this record.
     * @type {string}
     * @memberof Record
     */
    version: string;
    /**
     * Opaque business payload routed to the IO adapter.
     * @type {{ [key: string]: any; }}
     * @memberof Record
     */
    payload: { [key: string]: any; };
}

/**
 * Check if a given object implements the Record interface.
 */
export function instanceOfRecord(value: object): value is Record {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    return true;
}

export function RecordFromJSON(json: any): Record {
    return RecordFromJSONTyped(json, false);
}

export function RecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): Record {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'model': json['model'],
        'version': json['version'],
        'payload': json['payload'],
    };
}

export function RecordToJSON(json: any): Record {
    return RecordToJSONTyped(json, false);
}

export function RecordToJSONTyped(value?: Record | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'model': value['model'],
        'version': value['version'],
        'payload': value['payload'],
    };
}

