/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecordQueryCondition
 */
export interface RecordQueryCondition {
    /**
     * Field path such as `id` or `payload.record_scope`.
     * @type {string}
     * @memberof RecordQueryCondition
     */
    field: string;
    /**
     * Comparison operator.
     * @type {string}
     * @memberof RecordQueryCondition
     */
    op: RecordQueryConditionOpEnum;
    /**
     * Operand value. For `in` this must be an array. For `exists` this should be boolean.
     * @type {any}
     * @memberof RecordQueryCondition
     */
    value: any | null;
}


/**
 * @export
 */
export const RecordQueryConditionOpEnum = {
    Eq: 'eq',
    Ne: 'ne',
    In: 'in',
    Contains: 'contains',
    Exists: 'exists',
    Gt: 'gt',
    Gte: 'gte',
    Lt: 'lt',
    Lte: 'lte'
} as const;
export type RecordQueryConditionOpEnum = typeof RecordQueryConditionOpEnum[keyof typeof RecordQueryConditionOpEnum];


/**
 * Check if a given object implements the RecordQueryCondition interface.
 */
export function instanceOfRecordQueryCondition(value: object): value is RecordQueryCondition {
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('op' in value) || value['op'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function RecordQueryConditionFromJSON(json: any): RecordQueryCondition {
    return RecordQueryConditionFromJSONTyped(json, false);
}

export function RecordQueryConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordQueryCondition {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'],
        'op': json['op'],
        'value': json['value'],
    };
}

export function RecordQueryConditionToJSON(json: any): RecordQueryCondition {
    return RecordQueryConditionToJSONTyped(json, false);
}

export function RecordQueryConditionToJSONTyped(value?: RecordQueryCondition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'op': value['op'],
        'value': value['value'],
    };
}

