/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecordQuerySort
 */
export interface RecordQuerySort {
    /**
     * Sortable field path such as `created_at` or `payload.record_scope`.
     * @type {string}
     * @memberof RecordQuerySort
     */
    field: string;
    /**
     * Sort direction.
     * @type {string}
     * @memberof RecordQuerySort
     */
    direction: RecordQuerySortDirectionEnum;
}


/**
 * @export
 */
export const RecordQuerySortDirectionEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type RecordQuerySortDirectionEnum = typeof RecordQuerySortDirectionEnum[keyof typeof RecordQuerySortDirectionEnum];


/**
 * Check if a given object implements the RecordQuerySort interface.
 */
export function instanceOfRecordQuerySort(value: object): value is RecordQuerySort {
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    return true;
}

export function RecordQuerySortFromJSON(json: any): RecordQuerySort {
    return RecordQuerySortFromJSONTyped(json, false);
}

export function RecordQuerySortFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordQuerySort {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'],
        'direction': json['direction'],
    };
}

export function RecordQuerySortToJSON(json: any): RecordQuerySort {
    return RecordQuerySortToJSONTyped(json, false);
}

export function RecordQuerySortToJSONTyped(value?: RecordQuerySort | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'direction': value['direction'],
    };
}

