/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecordQuerySort } from './RecordQuerySort';
import {
    RecordQuerySortFromJSON,
    RecordQuerySortFromJSONTyped,
    RecordQuerySortToJSON,
    RecordQuerySortToJSONTyped,
} from './RecordQuerySort';
import type { RecordQueryCondition } from './RecordQueryCondition';
import {
    RecordQueryConditionFromJSON,
    RecordQueryConditionFromJSONTyped,
    RecordQueryConditionToJSON,
    RecordQueryConditionToJSONTyped,
} from './RecordQueryCondition';

/**
 * Canonical backend query dialect shared across record store adapters.
 * @export
 * @interface RecordQueryFilter
 */
export interface RecordQueryFilter {
    /**
     * AND-only list of query predicates.
     * @type {Array<RecordQueryCondition>}
     * @memberof RecordQueryFilter
     */
    where: Array<RecordQueryCondition>;
    /**
     * Optional list of sort directives applied in order.
     * @type {Array<RecordQuerySort>}
     * @memberof RecordQueryFilter
     */
    sort?: Array<RecordQuerySort>;
    /**
     * Maximum number of records to return.
     * @type {number}
     * @memberof RecordQueryFilter
     */
    limit?: number;
    /**
     * Zero-based row offset for pagination.
     * @type {number}
     * @memberof RecordQueryFilter
     */
    offset?: number;
}

/**
 * Check if a given object implements the RecordQueryFilter interface.
 */
export function instanceOfRecordQueryFilter(value: object): value is RecordQueryFilter {
    if (!('where' in value) || value['where'] === undefined) return false;
    return true;
}

export function RecordQueryFilterFromJSON(json: any): RecordQueryFilter {
    return RecordQueryFilterFromJSONTyped(json, false);
}

export function RecordQueryFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordQueryFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'where': ((json['where'] as Array<any>).map(RecordQueryConditionFromJSON)),
        'sort': json['sort'] == null ? undefined : ((json['sort'] as Array<any>).map(RecordQuerySortFromJSON)),
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
    };
}

export function RecordQueryFilterToJSON(json: any): RecordQueryFilter {
    return RecordQueryFilterToJSONTyped(json, false);
}

export function RecordQueryFilterToJSONTyped(value?: RecordQueryFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'where': ((value['where'] as Array<any>).map(RecordQueryConditionToJSON)),
        'sort': value['sort'] == null ? undefined : ((value['sort'] as Array<any>).map(RecordQuerySortToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

