/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidateRequest
 */
export interface ValidateRequest {
    /**
     * Candidate record payload to validate.
     * @type {{ [key: string]: any; }}
     * @memberof ValidateRequest
     */
    payload: { [key: string]: any; };
}

/**
 * Check if a given object implements the ValidateRequest interface.
 */
export function instanceOfValidateRequest(value: object): value is ValidateRequest {
    if (!('payload' in value) || value['payload'] === undefined) return false;
    return true;
}

export function ValidateRequestFromJSON(json: any): ValidateRequest {
    return ValidateRequestFromJSONTyped(json, false);
}

export function ValidateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'payload': json['payload'],
    };
}

export function ValidateRequestToJSON(json: any): ValidateRequest {
    return ValidateRequestToJSONTyped(json, false);
}

export function ValidateRequestToJSONTyped(value?: ValidateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payload': value['payload'],
    };
}

