/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationResult } from './ValidationResult';
import {
    ValidationResultFromJSON,
    ValidationResultFromJSONTyped,
    ValidationResultToJSON,
    ValidationResultToJSONTyped,
} from './ValidationResult';

/**
 * 
 * @export
 * @interface ValidationReport
 */
export interface ValidationReport {
    /**
     * True when no blocking validation issues were found.
     * @type {boolean}
     * @memberof ValidationReport
     */
    passed: boolean;
    /**
     * 
     * @type {Array<ValidationResult>}
     * @memberof ValidationReport
     */
    results: Array<ValidationResult>;
}

/**
 * Check if a given object implements the ValidationReport interface.
 */
export function instanceOfValidationReport(value: object): value is ValidationReport {
    if (!('passed' in value) || value['passed'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ValidationReportFromJSON(json: any): ValidationReport {
    return ValidationReportFromJSONTyped(json, false);
}

export function ValidationReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationReport {
    if (json == null) {
        return json;
    }
    return {
        
        'passed': json['passed'],
        'results': ((json['results'] as Array<any>).map(ValidationResultFromJSON)),
    };
}

export function ValidationReportToJSON(json: any): ValidationReport {
    return ValidationReportToJSONTyped(json, false);
}

export function ValidationReportToJSONTyped(value?: ValidationReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'passed': value['passed'],
        'results': ((value['results'] as Array<any>).map(ValidationResultToJSON)),
    };
}

