/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hexagonal Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationResult
 */
export interface ValidationResult {
    /**
     * JSON path or pointer of the failing field when available.
     * @type {string}
     * @memberof ValidationResult
     */
    path?: string;
    /**
     * Human-readable validation message.
     * @type {string}
     * @memberof ValidationResult
     */
    message?: string;
    /**
     * Validation severity label when provided by validator.
     * @type {string}
     * @memberof ValidationResult
     */
    severity?: string;
}

/**
 * Check if a given object implements the ValidationResult interface.
 */
export function instanceOfValidationResult(value: object): value is ValidationResult {
    return true;
}

export function ValidationResultFromJSON(json: any): ValidationResult {
    return ValidationResultFromJSONTyped(json, false);
}

export function ValidationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationResult {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'] == null ? undefined : json['path'],
        'message': json['message'] == null ? undefined : json['message'],
        'severity': json['severity'] == null ? undefined : json['severity'],
    };
}

export function ValidationResultToJSON(json: any): ValidationResult {
    return ValidationResultToJSONTyped(json, false);
}

export function ValidationResultToJSONTyped(value?: ValidationResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'message': value['message'],
        'severity': value['severity'],
    };
}

