/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VersionResponse
 */
export interface VersionResponse {
    /**
     * Stable service identifier.
     * @type {string}
     * @memberof VersionResponse
     */
    service: string;
    /**
     * Running service build version from crate metadata.
     * @type {string}
     * @memberof VersionResponse
     */
    serviceVersion: string;
    /**
     * Bundled OpenAPI document version from info.version.
     * @type {string}
     * @memberof VersionResponse
     */
    openapiVersion: string;
}

/**
 * Check if a given object implements the VersionResponse interface.
 */
export function instanceOfVersionResponse(value: object): value is VersionResponse {
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('serviceVersion' in value) || value['serviceVersion'] === undefined) return false;
    if (!('openapiVersion' in value) || value['openapiVersion'] === undefined) return false;
    return true;
}

export function VersionResponseFromJSON(json: any): VersionResponse {
    return VersionResponseFromJSONTyped(json, false);
}

export function VersionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'],
        'serviceVersion': json['service_version'],
        'openapiVersion': json['openapi_version'],
    };
}

export function VersionResponseToJSON(json: any): VersionResponse {
    return VersionResponseToJSONTyped(json, false);
}

export function VersionResponseToJSONTyped(value?: VersionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'service_version': value['serviceVersion'],
        'openapi_version': value['openapiVersion'],
    };
}

