/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hexagonal Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateRequest
 */
export interface CreateRequest {
    /**
     * Payload to validate and persist as a new record.
     * @type {{ [key: string]: any; }}
     * @memberof CreateRequest
     */
    'payload': { [key: string]: any; };
}

