/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hexagonal Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * Stable machine-readable error code.
     * @type {string}
     * @memberof ErrorResponse
     */
    'code': string;
    /**
     * Human-readable error message.
     * @type {string}
     * @memberof ErrorResponse
     */
    'message': string;
    /**
     * Optional error details payload.
     * @type {any}
     * @memberof ErrorResponse
     */
    'details'?: any | null;
}

