/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hex Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Record
 */
export interface Record {
    /**
     * Record identifier returned by the store adapter.
     * @type {string}
     * @memberof Record
     */
    'id': string;
    /**
     * Model identifier used for this record.
     * @type {string}
     * @memberof Record
     */
    'model': string;
    /**
     * Model version used for this record.
     * @type {string}
     * @memberof Record
     */
    'version': string;
    /**
     * Opaque business payload routed to the IO adapter.
     * @type {{ [key: string]: any; }}
     * @memberof Record
     */
    'payload': { [key: string]: any; };
}

