/* tslint:disable */
/* eslint-disable */
/**
 * CE-RISE Hexagonal Core Service API
 * Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ValidationResult } from './validation-result';

/**
 * 
 * @export
 * @interface ValidationReport
 */
export interface ValidationReport {
    /**
     * True when no blocking validation issues were found.
     * @type {boolean}
     * @memberof ValidationReport
     */
    'passed': boolean;
    /**
     * 
     * @type {Array<ValidationResult>}
     * @memberof ValidationReport
     */
    'results': Array<ValidationResult>;
}

